name: animation
description: Animation
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  flutter:
    sdk: flutter
  shimmer: ^3.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.3
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_monfadev.png"

flutter:
  uses-material-design: true
  assets:
    - assets/