name: animation
description: Animation
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  liquid_progress_indicator: ^0.4.0
  shimmer: ^2.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_svg: ^0.22.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_monfadev.png"

flutter:
  uses-material-design: true
  assets:
    - assets/